---
name: rental_camera_admin
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  responsive_sizer: ^3.1.1
  cloud_firestore: ^4.8.0
  google_fonts: any
  provider: any
  file_picker: ^4.6.1
  url_launcher: ^6.1.2
  loading_overlay: ^0.3.0
  firebase_storage: ^11.2.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
